services:
  bookmarker-app-green:
    build: .
    container_name: bookmarker-app-green
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=bookmarker-redis # 컨테이너 명
      - SPRING_REDIS_PORT=6379
      - TZ=Asia/Seoul
      - LOGGING_LEVEL_ROOT=DEBUG  # 디버깅
    volumes:
      - ./logs:/app/logs
    depends_on:
      - bookmarker-redis
    networks:
      - bookmarker-net

networks:
  bookmarker-net:
    external: true