spring.application.name=bookmarker
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.mvc.favicon.enabled=false
server.tomcat.uri-encoding=UTF-8

server.servlet.context-path=/

library.api.key=${LIBRARY_API_KEY}
sha.salt.key=${SHA_SALT}