version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: bookMarker:latest
    ports:
      - "8088:8088"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

