name: Deploy aws ec2 docker ci/cd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build bootJar
        run: ./gradlew bootJar -x test

      # bootJar ec2로 scp 전송
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          port: ${{ secrets.EC2_PORT }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ec2-user/docker"
          strip_components: 2
      # deploy.sh ec2로 scp 전송
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          port: ${{ secrets.EC2_PORT }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".github/workflows/deploy.sh"
          target: "/home/ec2-user/docker"
          strip_components: 2
      # dockerfile, compose ec2로 scp 전송
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          port: ${{ secrets.EC2_PORT }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "Dockerfile,docker-compose.blue.yml,docker-compose.green.yml,docker-compose.redis.yml"
          target: "/home/ec2-user/docker"

      # ssh 실행 스크립트 최신버전 백업 -> 빌드 -> 구이미지 삭제
      - name: Deploy SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          port: ${{ secrets.EC2_PORT }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/docker
            # nginx용 deploy 실행
            ./deploy.sh
            # 구 이미지 삭제
            docker image prune -f
